---
# file: docker-engine/tasks/apt.yml

# prepare system for the official Docker APT repository
- name: Add Docker GPG repository key
  become: True
  apt_key:
    keyserver: '{{ docker_engine_gpg_keyserver }}'
    id: '{{ docker_engine_gpg_key_id }}'
    state: 'present'
  tags:
    - 'docker-engine'

- name: Add Docker official repository
  become: True
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: 'present'
  tags:
    - 'docker-engine'

- name: Update APT cache
  become: True
  apt:
    update_cache: True
    cache_valid_time: '{{ 60 * 60 * 24 }}' # cache is valid for 24 hours
  tags:
    - 'docker-engine'

# install package
- name: Install docker-engine package via apt from official Docker repository
  become: True
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    name: '{{ docker_engine_package_name }}{% if docker_engine_package_install_version %}={{ docker_engine_package_install_version }}{% endif %}'
    state: '{% if docker_engine_package_install_latest %}latest{% else %}present{% endif %}'
  tags:
    - 'docker-engine'
    - 'docker-engine-packages'
