---
# file: docker-engine/tasks/main.yml

# delegate installation to the specific package manager
- include: '{{ ansible_pkg_mgr }}.yml'


- name: Make sure Docker engine configuration folder exists
  become: True
  file:
    name: '/etc/docker'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags:
    - 'docker-engine'
    - 'docker-engine-config'

- name: Configure Docker engine
  become: True
  copy:
    content: "{{ docker_engine_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Docker engine
  tags:
    - 'docker-engine'
    - 'docker-engine-config'

- name: Flush all handlers before ensuring service is started and enabled
  meta: flush_handlers
  tags:
    - 'docker-engine'

- name: Enable Docker Engine service
  become: True
  service:
    name: '{{ docker_engine_service_name }}'
    state: 'started'
    enabled: True
  tags:
    - 'docker-engine'

- name: Grant access to the local docker engine
  become: True
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: True
  loop: '{{ docker_engine_docker_users }}'
  tags:
    - 'docker-engine'
