- name: Create Grafana volume
  docker_volume:
    name: grafana-storage

- name: Start Grafana Container
  docker_container:
    name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    networks_cli_compatible: yes
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"