version: "3.2"
services:
  nmn-client:
    container_name: client
    image: newamericapocacr.azurecr.io/oars-client:latest
    ports:
      - "8080:8080"
    environment:
      - "SERVER_PORT=8080"
      - "CONFIG_RPC_USERNAME=user1"
      - "CONFIG_RPC_PASSWORD=test"
      - "CONFIG_RPC_HOST=host.docker.internal"
      - "CONFIG_RPC_PORT=10009"