- name: Create Corda Directory
  file:
    owner: corda
    group: root
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ corda_node_full_path }}/"
    - "{{ corda_node_full_path }}/certificates"
    - "{{ corda_node_full_path }}/config"
    - "{{ corda_node_full_path }}/persistence"
    - "{{ corda_node_full_path }}/logs"
    - "{{ corda_node_full_path }}/cordapps"
    - "{{ corda_node_full_path }}/cordapps/config"
    - "{{ corda_node_full_path }}/drivers"
    - "{{ corda_node_full_path }}/migration"

#- name: Create Postgres Directory
#  file:
#    owner: corda
#    group: root
#    path: "{{ item }}"
#    state: directory
#  with_items:
#    - "/opt/corda/{{ corda_node_name }}_db"
#    - "/opt/corda/{{ corda_node_name }}_db/sql"
#    - "/opt/corda/{{ corda_node_name }}_db/backups"
##    - "/opt/corda/{{ corda_node_name }}_db/data"

#- name: Copy network-root-truststore.jks File
#  copy:
#    src: files/certificates/{{ env }}/network-root-truststore.jks
#    dest: "{{ corda_node_full_path }}/certificates"

#- name: Download HA-Utilities Tool
#  get_url:
#    url: "{{ artifactory_corda_base_url }}/com/r3/corda/corda-tools-ha-utilities/4.4/corda-tools-ha-utilities-4.4.jar"
#    dest: "{{ corda_node_full_path }}/corda-tools-ha-utilities.jar"
#    username: "{{ artifactory_username }}"
#    password: "{{ artifactory_password }}"

#- name: Download Postgres Driver
#  get_url:
#    url: https://jdbc.postgresql.org/download/postgresql-42.2.12.jar
#    dest: "{{ corda_node_full_path }}/drivers/postgresql-42.2.12.jar"
#
#- name: Download Prometheus Driver
#  get_url:
#    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.13.0/jmx_prometheus_javaagent-0.13.0.jar
#    dest: "{{ corda_node_full_path }}/drivers/jmx_prometheus_javaagent-0.13.0.jar"
#  when: prometheus_enabled
#
#- name: Copy Promtheus Configuration
#  template:
#    src: prometheus_config.yml.j2
#    dest: "{{ corda_node_full_path }}/drivers/config.yml"
#    owner: root
#    group: root
#    mode: 0644
#    backup: no
#  when: prometheus_enabled

#- name: Copy corda.jar #3.3.20200331
#  copy:
#    owner: root
#    group: root
#    src: "files/{{ env }}/corda3/corda.jar"
#    dest: "/opt/corda/{{ corda_node_name }}/corda.jar"

#- name: Copy corda.jar #4.4.3-PREVIEW
#  copy:
#    owner: root
#    group: root
#    src: "files/{{ env }}/corda4/corda.jar"
#    dest: "/opt/corda/{{ corda_node_name }}/corda.jar"

#- name: Copy Cordapp Jar Files
#  copy:
#    src: files/cordapps/{{ env }}/corda3/
#    dest: "{{ corda_node_full_path }}/cordapps"

- name: Copy Cordapp Jar Files
  copy:
    src: files/cordapps/{{ env }}/corda4/
    dest: "{{ corda_node_full_path }}/cordapps"

- name: Copy spunta.properties File
  copy:
    src: files/config/{{ env }}/spunta.properties
    dest: "{{ corda_node_full_path }}/spunta.properties"

- name: Download Corda Health Survey Jar
  get_url:
    url: "{{ artifactory_corda_base_url }}/com/r3/corda/corda-tools-health-survey/4.4.2/corda-tools-health-survey-4.4.2.jar"
    dest: "{{ corda_node_full_path }}/corda-tools-health-survey.jar"
    username: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"