- name: Start Filebeat Container
  docker_container:
    name: "{{ corda_node_name }}_fb"
    hostname: "{{ corda_node_name }}_fb"
    image: docker.elastic.co/beats/filebeat:7.7.1
    networks_cli_compatible: yes
    volumes:
      - "/opt/corda/filebeat/filebeat_{{ corda_node_name }}.yml:/usr/share/filebeat/filebeat.yml"
      - "{{ corda_node_full_path }}/logs:/var/log/{{ corda_node_name }}/node"
      - "{{ corda_node_full_path }}_batch/logs:/var/log/{{ corda_node_name }}/batch"
      - "{{ corda_node_full_path }}_aux/logs:/var/log/{{ corda_node_name }}/ws"
    env:
      setup.kibaba.host: "10.0.1.4:5601"
      output.elasticsearch.hosts: "10.0.1.4:9200"