# 06-stop-client.yml
---
- name: Stop Corda Client
  hosts: node-machines
  gather_facts: true
  become: true
  tasks:
    - name: Stop Client Docker Container
      docker_container:
        name: "client-{{ inventory_hostname }}"
        hostname: "client-{{ inventory_hostname }}"
        image: "{{ docker_registry_url }}/{{ docker_image_api }}:{{ docker_image_api_version }}"
        state: stopped
      tags:
        - stop-client
    - name: Remove Client Docker Container
      docker_container:
        name: "client-{{ inventory_hostname }}"
        hostname: "client-{{ inventory_hostname }}"
        image: "{{ docker_registry_url }}/{{ docker_image_api }}:{{ docker_image_api_version }}"
        state: absent
      tags:
        - remove-client