docker_registry_url: newamericaacrprod.azurecr.io
docker_registry_username: newamericaacrprod
docker_registry_password: r92I55u1hzPRm99o/q8od0yROm/Cc56o

docker_image_ui: oars-ui
docker_image_ui_version: latest

api_url: node-oars.eastus.cloudapp.azure.com
keycloak_url: secure-oars.eastus.cloudapp.azure.com
keycloak_client_id: oars-client