- name: Create Nginx Directory
  file:
    owner: corda
    group: root
    path: "{{ item }}"
    state: directory
  with_items:
    - "/opt/nginx"
  tags:
    - create-nginx-directory

- name: Copy Nginx Config
  template:
    src: nginx.conf.j2
    dest: "/opt/nginx/default.conf"
    owner: corda
    group: root
    mode: 0644
    backup: no