# 01-install-dependencies.yml
---
- name: Install Dependencies
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: common
    - role: docker-engine
      vars:
        - docker_engine_package_version: 'latest'
#    - role: jdk-zulu
#      vars:
#        - jdk_zulu_package_version: 8.33.0.1
  tags:
    - install-dependencies