# 03-start-nodes.yml
---
- name: Start Corda Nodes
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Create Docker Network
      docker_network:
        name: corda
    - name: Start Corda Docker Container
      docker_container:
        name: "node-{{ inventory_hostname }}"
        hostname: "node-{{ inventory_hostname }}"
        image: "{{ corda_docker_image_version }}"
        state: started
        networks:
          - name: corda
        networks_cli_compatible: yes
        ports:
          - 10200:10200
          - 10201:10201
          - 2222:2222
        volumes:
          - "/opt/corda/config:/etc/corda"
          - "/opt/corda/additional-node-infos:/opt/corda/additional-node-infos"
          - "/opt/corda/certificates:/opt/corda/certificates"
          - "/opt/corda/persistence:/opt/corda/persistence"
          - "/opt/corda/logs:/opt/corda/logs"
          - "/opt/corda/cordapps:/opt/corda/cordapps"
          - "/opt/corda/drivers:/opt/corda/drivers"
          - "/opt/corda/network-parameters:/opt/corda/network-parameters"
  tags:
    - start-nodes