# 04-stop-nodes.yml
---
- name: Stop Nodes
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Stop Corda Docker Container
      docker_container:
        name: "node-{{ inventory_hostname }}"
        hostname: "node-{{ inventory_hostname }}"
        image: "{{ corda_docker_image_version }}"
        state: stopped
      tags:
        - stop-nodes
    - name: Remove Corda Docker Container
      docker_container:
        name: "node-{{ inventory_hostname }}"
        hostname: "node-{{ inventory_hostname }}"
        image: "{{ corda_docker_image_version }}"
        state: absent
      tags:
        - remove-nodes