# 10-install-cordapps.yml
---

- import_playbook: 04-stop-nodes.yml

- name: Install CorDapps
  hosts: node-machines
  gather_facts: true
  become: true
  tasks:
    - name: Copy CorDapps
      copy:
        src: files/cordapps/
        dest: /opt/corda/cordapps/
        owner: corda
        group: root
      tags:
        - copy-cordapps

- import_playbook: 03-start-nodes.yml