# 10-install-cordapps.yml
---
- name: Install CorDapps
  hosts: node-machines
  gather_facts: true
  become: true
  tasks:
    - name: Stop Corda Docker Container
      docker_container:
        name: corda-node
        hostname: corda-node
        image: "{{ corda_docker_image_version }}"
        state: stopped
    - name: Copy CorDapps
      copy:
        src: files/cordapps/
        dest: /opt/corda/cordapps/
        owner: corda
        group: root
    - name: Start Corda Docker Container
      docker_container:
        name: corda-node
        hostname: corda-node
        image: "{{ corda_docker_image_version }}"
        state: started