# 100-clean-environment.yml
---
- name: Clean Environment
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Stop Corda Docker Container
      docker_container:
        name: corda-node
        hostname: corda-node
        image: "{{ corda_docker_image_version }}"
        state: stopped
    - name: Remove Directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/opt/corda/certificates"
        - "/opt/corda/cordapps"
        - "/opt/corda/additional-node-infos"
        - "/opt/corda/config"
        - "/opt/corda/logs"
        - "/opt/corda/network-parameters"
        - "/opt/corda/nodeInfo-*"
        - "/opt/corda/persistence"
      tags:
        - remove-dirs