# 101-clean-dbs.yml
---
- name: Clean DB's
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Stop Corda Docker Container
      docker_container:
        name: "node-{{ inventory_hostname }}"
        hostname: "node-{{ inventory_hostname }}"
        image: "{{ corda_docker_image_version }}"
        state: stopped
    - name: Remove Directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/opt/corda/persistence/persistence.mv.db"
        - "/opt/corda/persistence/persistence.trace.db"
      tags:
        - remove-dirs
    - name: Remove Docker Container
      docker_container:
        name: "node-{{ inventory_hostname }}"
        hostname: "node-{{ inventory_hostname }}"
        image: "{{ corda_docker_image_version }}"
        state: absent
      tags:
        - remove-corda