# 20-start-ui.yml
---
- name: Start UI
  hosts: node-machines
  gather_facts: true
  become: true
  tasks:
    - name: Docker Login
      docker_login:
        registry: "{{ docker_registry_url }}"
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
    - name: Start UI Container
      docker_container:
        name: ui
        hostname: ui
        image: "{{ docker_registry_url }}/{{ docker_image_ui }}:{{ docker_image_ui_version }}"
        pull: true
        state: started
        networks:
          - name: corda
        networks_cli_compatible: yes
        ports:
          - 80:80