# 21-stop-ui.yml
---
- name: Stop UI
  hosts: ui-machines
  gather_facts: false
  become: true
  tasks:
    - name: Stop UI Container
      docker_container:
        name: "oars-ui"
        hostname: "oars-ui"
        image: "{{ docker_registry_url }}/{{ docker_image_ui }}:{{ docker_image_ui_version }}"
        state: stopped
      tags:
        - stop-ui
    - name: Remove UI Container
      docker_container:
        name: "oars-ui"
        hostname: "oars-ui"
        image: "{{ docker_registry_url }}/{{ docker_image_ui }}:{{ docker_image_ui_version }}"
        state: absent
      tags:
        - remove-ui
