# 90-docker-swarm.yml
---
- name: Docker Swarm
  hosts: keycloak
  gather_facts: true
  become: true
  tasks:
    - name: Initialise Docker Swarm
      docker_swarm:
        state: present
    - name: Create Overlay Network
      docker_network:
        name: oars
        attachable: true
        driver: overlay
        state: present
        ipam_config:
          - subnet: 10.1.0.0/24
  tags:
    - create-swarm

- name: Docker Swarm
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Join Docker Swarm
      docker_swarm:
        state: join
        advertise_addr: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
        join_token: SWMTKN-1-4g8jj1lw3jv8kej79i4ibbid49sf0wwa334y0puz44cjp3awt9-1u8c4mutdpsuvt81u99m4wmpu
        remote_addrs: [ '10.0.1.14:2377' ]
  tags:
    - join-swarm

- name: Docker Swarm
  hosts: node-machines, notary-machines
  gather_facts: true
  become: true
  tasks:
    - name: Leave Docker Swarm
      docker_swarm:
        state: absent
        force: true
  tags:
    - leave-swarm